name: Build and Test

on:
  push:
    branches:
      - main  # Change to your branch name if necessary

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]  # Replace with your desired Python version

      - name: Install dependencies
        run: pip install -r requirements.txt  # Replace with your dependencies installation command

      - name: Run tests
        run: python -m unittest discover  # Replace with your tests execution command
